### ISSUE TITLE
Fonction chooseEnemy() à déplacer

### ISSUE THREAD

**Issue by BhasherBEL** [yaelMagnier/ExplosePatate#11]
/strats/WEAPONSTART -> /tools/fonctions/LEEKS

**Comment by yaelMagnier** [comment]
Je suis pas sur que juste déplacer le fichier vers un nouveau fichier soit vraiement opti
Surtout qu'on doit rappeler le fichier mais bon, je fais ca

**Comment by BhasherBEL** [comment]
D'autres fonctions vont se rajouter. Et je pense que c'est plus propre.
